@ECHO OFF

SET BSOAGenerator="%~dp0bin\Release\netcoreapp3.1\BSOA.Generator.exe"
SET JSchemaToBsoaSchema="%~dp0..\JschemaToBsoaSchema\bin\Release\netcoreapp3.1\JSchemaToBsoaSchema.exe"
PUSHD %~dp0

ECHO Generating Unit Test models...
%BSOAGenerator% "Schemas\Person.UnitTest.V1.schema.json" "..\BSOA.Test\Model\V1"
%BSOAGenerator% "Schemas\Person.UnitTest.V2.schema.json" "..\BSOA.Test\Model\V2"

ECHO Generating Sarif SDK model...
%JSchemaToBsoaSchema% "..\..\..\..\sarif-sdk-bsoa\src\Sarif\Schemata\sarif-2.1.0-rtm.5.json" "..\BSOA.Generator\Schemas\Sarif-2.1.0-rtm.5.schema.json"

::%BSOAGenerator% "Schemas\Sarif-2.1.0-rtm.5.schema.json" "..\..\..\..\sarif-sdk-bsoa\src\Sarif\Autogenerated" "Templates\Sarif"
%BSOAGenerator% "Schemas\Sarif-2.1.0-rtm.5.schema.json" "..\Sarif.SDK.BSOA\Autogenerated" "Templates\Sarif"

POPD